# Site settings
name: Eric Mey
email: ericmey@gmail.com
description: Code and ninja skills...
url: "https://ericmey.github.io"
repository: ericmey
twitter_username: ericmey
github_username: ericmey

# Build settings
exclude: ["Gemfile", "Gemfile.lock", "gulpfile.babel.js", "LICENSE", "node_modules", "package.json", "README.md"]

gems:
  - jekyll-sitemap
  - jekyll-github-metadata
